// Generated by scripts/generate.mjs. Do not edit by hand — run: npm run seed
export const sources = [
  {
    "id": "s1",
    "filename": "intake-interview-2026-03-11.txt",
    "kind": "plain text",
    "category": "self-report",
    "meta": "interview transcript · 4,180 words",
    "excerpt": "[00:14:22] Q: How long have you been doing land work?\nA: Fourteen years now. Started in 2012 doing ranch\nsplits out past Hondo, moved into mineral and\nsurface severance work about four years in.\n\n[00:31:07] A: The parcel database is mine. I built it,\nI host it, I run the nightly pull myself.\n\n[00:52:41] Q: Team size on the Atascosa cycle?\nA: Three of us. Me, a title clerk, and a surveyor\non contract."
  },
  {
    "id": "s2",
    "filename": "deed-records-medina-frio-atascosa.csv",
    "kind": "csv export",
    "category": "third-party record",
    "meta": "county clerk pull · 1,284 rows",
    "excerpt": "county,instrument,date,role,acres,mineral_severed\nMedina,WD-2024-04188,2024-06-11,buyer_rep,212.4,true\nFrio,WD-2024-05512,2024-09-02,seller_rep,64.0,false\nAtascosa,WD-2025-00913,2025-02-20,buyer_rep,341.7,true\n… 49 more rows matching role filter\n\n-- 52 rows where role is buyer_rep or seller_rep\n-- 17 of those with mineral_severed = true"
  },
  {
    "id": "s3",
    "filename": "degree-verification-2019.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "registrar letter · 1 page",
    "excerpt": "This letter confirms that A. Reyes was awarded the\ndegree of Master of Science in Land Economics,\nconferred 2019-05-18. Degree is in good standing.\n\nIssued at the request of the degree holder."
  },
  {
    "id": "s4",
    "filename": "parcel-db-commit-log.txt",
    "kind": "plain text",
    "category": "system export",
    "meta": "version control export · 412 commits",
    "excerpt": "repository    parcel-db\nfirst commit  2025-11-04\nlast commit   2026-08-19\ncommits       412\nauthors       1  (a.reyes)\nhosting       self, single node\nnightly job   county-ingest · 287 successful runs"
  },
  {
    "id": "s5",
    "filename": "performance-review-2026-02-09.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 9 pages",
    "excerpt": "Reference PERFORMANCEREVIEW-6327\nIssued 2026-02-09.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s6",
    "filename": "employment-verification-2025-04-18.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 4 pages",
    "excerpt": "Reference EMPLOYMENTVERIFICATION-2469\nIssued 2025-04-18.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s7",
    "filename": "reference-letter-2025-07-29.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 2 pages",
    "excerpt": "Reference REFERENCELETTER-6463\nIssued 2025-07-29.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s8",
    "filename": "offer-letter-2026-03-30.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 4 pages",
    "excerpt": "Reference OFFERLETTER-2872\nIssued 2026-03-30.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s9",
    "filename": "course-transcript-2026-06-24.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 5 pages",
    "excerpt": "Reference COURSETRANSCRIPT-7802\nIssued 2026-06-24.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s10",
    "filename": "license-history-2026-05-11.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 1 pages",
    "excerpt": "Reference LICENSEHISTORY-3297\nIssued 2026-05-11.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s11",
    "filename": "certification-card-2026-03-30.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 6 pages",
    "excerpt": "Reference CERTIFICATIONCARD-3645\nIssued 2026-03-30.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s12",
    "filename": "continuing-ed-credits-2025-04-18.csv",
    "kind": "csv export",
    "category": "third-party record",
    "meta": "export · 1,958 rows",
    "excerpt": "issued_on,item,units,verified\n2025-04-18,continuing_ed_credits,18,true\n… 20 more rows\n\n-- issued by the awarding body, not by the subject"
  },
  {
    "id": "s13",
    "filename": "client-note-2025-09-14.txt",
    "kind": "plain text",
    "category": "third-party record",
    "meta": "record · 5,606 words",
    "excerpt": "Reference CLIENTNOTE-9081\nIssued 2025-09-14.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s14",
    "filename": "award-letter-2026-02-09.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 3 pages",
    "excerpt": "Reference AWARDLETTER-2469\nIssued 2026-02-09.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s15",
    "filename": "contract-sow-2026-03-30.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 2 pages",
    "excerpt": "Reference CONTRACTSOW-7268\nIssued 2026-03-30.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s16",
    "filename": "earnings-summary-2026-02-09.csv",
    "kind": "csv export",
    "category": "third-party record",
    "meta": "export · 858 rows",
    "excerpt": "issued_on,item,units,verified\n2026-02-09,earnings_summary,31,true\n… 89 more rows\n\n-- issued by the awarding body, not by the subject"
  },
  {
    "id": "s17",
    "filename": "timesheet-export-2025-07-29.csv",
    "kind": "csv export",
    "category": "system export",
    "meta": "export · 780 rows",
    "excerpt": "exported_on,timesheet_export,count\n2025-07-29,total,295\n2025-07-29,flagged,9\n… 42 more rows\n\n-- generated by the system, not typed by hand"
  },
  {
    "id": "s18",
    "filename": "closing-tracker-2025-04-18.csv",
    "kind": "csv export",
    "category": "system export",
    "meta": "export · 565 rows",
    "excerpt": "exported_on,closing_tracker,count\n2025-04-18,total,365\n2025-04-18,flagged,37\n… 71 more rows\n\n-- generated by the system, not typed by hand"
  },
  {
    "id": "s19",
    "filename": "mileage-log-2026-01-22.csv",
    "kind": "csv export",
    "category": "system export",
    "meta": "export · 2,252 rows",
    "excerpt": "exported_on,mileage_log,count\n2026-01-22,total,769\n2026-01-22,flagged,14\n… 75 more rows\n\n-- generated by the system, not typed by hand"
  },
  {
    "id": "s20",
    "filename": "project-log-2026-02-09.txt",
    "kind": "plain text",
    "category": "self-report",
    "meta": "own notes · 3,100 words",
    "excerpt": "Written 2026-02-09.\n\n28 entries, kept by the subject for their own\nreference. Useful for recall. Not evidence on its\nown — nothing here was checked by anyone else."
  },
  {
    "id": "s21",
    "filename": "work-sample-notes-2026-01-22.txt",
    "kind": "plain text",
    "category": "self-report",
    "meta": "own notes · 5,067 words",
    "excerpt": "Written 2026-01-22.\n\n12 entries, kept by the subject for their own\nreference. Useful for recall. Not evidence on its\nown — nothing here was checked by anyone else."
  },
  {
    "id": "s22",
    "filename": "deal-sheet-2026-03-30.txt",
    "kind": "plain text",
    "category": "self-report",
    "meta": "own notes · 5,537 words",
    "excerpt": "Written 2026-03-30.\n\n26 entries, kept by the subject for their own\nreference. Useful for recall. Not evidence on its\nown — nothing here was checked by anyone else."
  },
  {
    "id": "s23",
    "filename": "career-questionnaire-2025-11-06.txt",
    "kind": "plain text",
    "category": "self-report",
    "meta": "own notes · 2,656 words",
    "excerpt": "Written 2025-11-06.\n\n36 entries, kept by the subject for their own\nreference. Useful for recall. Not evidence on its\nown — nothing here was checked by anyone else."
  },
  {
    "id": "s0",
    "filename": "— no record —",
    "kind": "none",
    "category": "none",
    "meta": "nothing in the library",
    "excerpt": "No record in the library supports this claim.\n\nText traced to: resume-2025-draft.docx\n\nThat file is an earlier document this pipeline wrote.\nA derived document cannot be cited as a source —\nciting it would mean the system vouching for itself."
  }
];

export const requirements = [
  {
    "id": "r1",
    "title": "Land transaction experience",
    "priority": "must",
    "verbatim": "5+ years originating, negotiating or closing land transactions in Texas. Familiarity with severed mineral estates strongly preferred.",
    "evidence": "intake-interview-2026-03-11.txt at 00:14:22 — fourteen years, starting 2012. Corroborated by deed-records-medina-frio-atascosa.csv: 52 closings across three counties, 17 with a severed mineral estate.",
    "verdict": "have as documented"
  },
  {
    "id": "r2",
    "title": "Parcel data systems",
    "priority": "must",
    "verbatim": "Comfort building or operating parcel-level data tooling — GIS layers, county record ingestion, or equivalent.",
    "evidence": "parcel-db-commit-log.txt — 412 commits, sole author, self-hosted, 287 nightly ingestion runs. The subject also describes it at 00:31:07 of intake-interview-2026-03-11.txt.",
    "verdict": "have as documented"
  },
  {
    "id": "r3",
    "title": "Interconnection queue familiarity",
    "priority": "preferred",
    "verbatim": "Working knowledge of the Sablewood Grid Authority generation interconnection queue and its study phases is preferred, not required.",
    "evidence": "Nothing in the library. A draft asserted fluency here; the assertion traced to resume-2025-draft.docx, a document this pipeline wrote, and was blocked at asset lint.",
    "verdict": "do not have"
  },
  {
    "id": "r4",
    "title": "Graduate degree",
    "priority": "preferred",
    "verbatim": "Advanced degree in real estate, economics, land use or a related field.",
    "evidence": "degree-verification-2019.pdf — registrar letter confirming M.S. Land Economics, conferred 2019-05-18, in good standing.",
    "verdict": "have as documented"
  },
  {
    "id": "r5",
    "title": "Team leadership",
    "priority": "must",
    "verbatim": "Experience leading a small cross-functional team through a full project cycle.",
    "evidence": "intake-interview-2026-03-11.txt at 00:52:41 — led three people through the Atascosa closing cycle. Cross-functional and a full cycle, but three, not six, and self-reported. The six-person figure has no record behind it at all.",
    "verdict": "adjacent but honest"
  }
];

export const documents = [
  {
    "id": "cover",
    "label": "cover letter",
    "kind": "letter",
    "blocks": [
      {
        "type": "meta",
        "text": "24 August 2026"
      },
      {
        "type": "meta",
        "text": "Hiring team\nMeridian Grid Partners\nSan Antonio, Texas"
      },
      {
        "type": "para",
        "text": "Dear hiring team,"
      },
      {
        "type": "para",
        "text": "I am writing about the site analyst opening posted on 11 August. I have {{c1}}, most of it on the parcel side of the work the posting describes: assembling positions in country where the surface and the minerals went separate ways decades ago, and where the person who signs is rarely the person on the tax roll."
      },
      {
        "type": "para",
        "text": "The transaction record is the part I would want checked first. County records show {{c2}}, acting for the buyer or the seller, and the instrument numbers are in an export I can send with this letter. Of those, {{c7}} — slower work than a clean fee transfer, and the reason I have firm opinions about how long title curative really takes."
      },
      {
        "type": "para",
        "text": "The posting also asks for comfort with parcel-level tooling. I {{c3}} that ingests county records nightly. I run the pull myself and I am {{c8}}, which is why I can usually answer an acreage or ownership question the same morning it is asked instead of a week later. I also hold an {{c4}}."
      },
      {
        "type": "para",
        "text": "On the interconnection side I bring {{c5}}, and {{c6}} through a full development cycle."
      },
      {
        "type": "para",
        "text": "What I would most want to discuss is where origination currently stalls for you — title curative, landowner contact, or the study phases — because the answer decides which of the above is actually worth anything to you. I am glad to walk through the parcel database on a call and let you push on the data yourself."
      },
      {
        "type": "para",
        "text": "Sincerely,"
      },
      {
        "type": "sig",
        "text": "A. Reyes"
      }
    ],
    "claims": [
      {
        "id": "c1",
        "text": "fourteen years working land transactions in South Texas",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r1"
      },
      {
        "id": "c2",
        "text": "52 closings across Medina, Frio and Atascosa counties",
        "label": "b",
        "sourceId": "s2",
        "requirementId": "r1"
      },
      {
        "id": "c3",
        "text": "built and self-host a parcel database",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r2"
      },
      {
        "id": "c4",
        "text": "M.S. in Land Economics",
        "label": "b",
        "sourceId": "s3",
        "requirementId": "r4"
      },
      {
        "id": "c5",
        "text": "deep familiarity with the Sablewood interconnection queue",
        "label": "d",
        "sourceId": "s0",
        "requirementId": "r3"
      },
      {
        "id": "c6",
        "text": "a documented record leading a six-person team",
        "label": "c",
        "sourceId": "s0",
        "requirementId": "r5"
      },
      {
        "id": "c7",
        "text": "17 involved a severed mineral estate",
        "label": "b",
        "sourceId": "s2",
        "requirementId": "r1"
      },
      {
        "id": "c8",
        "text": "its only committer",
        "label": "b",
        "sourceId": "s4",
        "requirementId": "r2"
      }
    ]
  },
  {
    "id": "resume",
    "label": "résumé",
    "kind": "resume",
    "blocks": [
      {
        "type": "name",
        "text": "A. Reyes"
      },
      {
        "type": "contact",
        "text": "San Antonio, Texas · a.reyes@example.invalid · (210) 555-0143"
      },
      {
        "type": "section",
        "text": "summary"
      },
      {
        "type": "para",
        "text": "{{c1}}, focused on ranch splits and severed mineral estates."
      },
      {
        "type": "section",
        "text": "experience"
      },
      {
        "type": "role",
        "text": "Senior land analyst · Tallow Creek Land Co",
        "meta": "2019 — present"
      },
      {
        "type": "bullet",
        "text": "{{c2}}, acting for the buyer or the seller"
      },
      {
        "type": "bullet",
        "text": "{{c3}} that ingests county records nightly"
      },
      {
        "type": "role",
        "text": "Land analyst · Bitterwater Ranch Company",
        "meta": "2012 — 2019"
      },
      {
        "type": "bullet",
        "text": "{{c5}} out of Hondo and the counties west of it"
      },
      {
        "type": "bullet",
        "text": "{{c6}} into the parcel database, unattended"
      },
      {
        "type": "section",
        "text": "education"
      },
      {
        "type": "bullet",
        "text": "{{c4}}, conferred 2019"
      }
    ],
    "claims": [
      {
        "id": "c1",
        "text": "Fourteen years in Texas land transactions",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r1"
      },
      {
        "id": "c2",
        "text": "52 closings across three counties",
        "label": "b",
        "sourceId": "s2",
        "requirementId": "r1"
      },
      {
        "id": "c3",
        "text": "Built and self-hosted a parcel database",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r2"
      },
      {
        "id": "c4",
        "text": "M.S. Land Economics",
        "label": "b",
        "sourceId": "s3",
        "requirementId": "r4"
      },
      {
        "id": "c5",
        "text": "Ranch splits and mineral severance work",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r1"
      },
      {
        "id": "c6",
        "text": "287 nightly ingestion runs",
        "label": "b",
        "sourceId": "s4",
        "requirementId": "r2"
      }
    ]
  },
  {
    "id": "outreach",
    "label": "outreach note",
    "kind": "note",
    "blocks": [
      {
        "type": "meta",
        "text": "to: hiring team, Meridian Grid Partners\nsubject: site analyst opening"
      },
      {
        "type": "para",
        "text": "I saw the site analyst opening. I have {{c1}}, and I {{c2}} — happy to show you what it pulls."
      },
      {
        "type": "para",
        "text": "Worth a short call?"
      },
      {
        "type": "sig",
        "text": "A. Reyes"
      }
    ],
    "claims": [
      {
        "id": "c1",
        "text": "spent fourteen years on Texas land deals",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r1"
      },
      {
        "id": "c2",
        "text": "run my own parcel database",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r2"
      }
    ]
  }
];

export const gates = {
  "gates": [
    {
      "id": "intake",
      "label": "intake",
      "rejects": "postings with no verbatim requirement text to quote"
    },
    {
      "id": "live",
      "label": "live check",
      "rejects": "postings that have closed or gone stale since intake"
    },
    {
      "id": "pressure",
      "label": "pressure test",
      "rejects": "applications where a must-have requirement lands on do not have"
    },
    {
      "id": "wildcard",
      "label": "wildcard question",
      "rejects": "applications with no honest answer to the open question in the posting"
    },
    {
      "id": "lint",
      "label": "asset lint",
      "rejects": "documents containing a claim labelled c or d"
    },
    {
      "id": "submitted",
      "label": "submitted",
      "rejects": "nothing — a record that reaches this gate has cleared every check"
    }
  ],
  "records": [
    {
      "id": "rec-01",
      "company": "Bosque Holdings",
      "role": "development associate",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s5",
        "s18"
      ],
      "stoppedAt": "intake",
      "verdicts": {
        "intake": "fail",
        "live": "not applicable",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-02",
      "company": "Frontage Development",
      "role": "right of way agent",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s6",
        "s19"
      ],
      "stoppedAt": "intake",
      "verdicts": {
        "intake": "fail",
        "live": "not applicable",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-03",
      "company": "Escarpment Development",
      "role": "development associate",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s4",
        "s7",
        "s20"
      ],
      "stoppedAt": "live",
      "verdicts": {
        "intake": "pass",
        "live": "expired",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-04",
      "company": "Salado Capital",
      "role": "land analyst",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s8",
        "s21"
      ],
      "stoppedAt": "live",
      "verdicts": {
        "intake": "pass",
        "live": "expired",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-05",
      "company": "Quarry Land Group",
      "role": "right of way agent",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s9",
        "s22"
      ],
      "stoppedAt": "pressure",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "blocked",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-06",
      "company": "Hardpan Development",
      "role": "land analyst",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s10",
        "s23"
      ],
      "stoppedAt": "pressure",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "blocked",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-07",
      "company": "Meridian Grid Partners",
      "role": "site analyst",
      "focus": true,
      "claimsParsed": 16,
      "claimsCleared": 14,
      "claimsBlocked": 2,
      "sourceIds": [
        "s1",
        "s2",
        "s3",
        "s4"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-08",
      "company": "Draw Holdings",
      "role": "parcel data lead",
      "focus": false,
      "claimsParsed": 1,
      "claimsCleared": 1,
      "claimsBlocked": 0,
      "sourceIds": [
        "s11"
      ],
      "stoppedAt": "wildcard",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "blocked",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-09",
      "company": "Frontage Capital",
      "role": "acquisition analyst",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 1,
      "claimsBlocked": 2,
      "sourceIds": [
        "s4",
        "s12"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-10",
      "company": "Ridgeline Energy",
      "role": "land analyst",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 2,
      "claimsBlocked": 1,
      "sourceIds": [
        "s1",
        "s13"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-11",
      "company": "Lometa Land Group",
      "role": "title analyst",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 1,
      "claimsBlocked": 1,
      "sourceIds": [
        "s14"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-12",
      "company": "Wallow Partners",
      "role": "land analyst",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s3",
        "s15"
      ],
      "stoppedAt": null,
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "pass",
        "submitted": "pass"
      }
    },
    {
      "id": "rec-13",
      "company": "Ridgeline Development",
      "role": "diligence analyst",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s16"
      ],
      "stoppedAt": null,
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "pass",
        "submitted": "pass"
      }
    },
    {
      "id": "rec-14",
      "company": "Lometa Development",
      "role": "title analyst",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s1",
        "s17"
      ],
      "stoppedAt": null,
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "pass",
        "submitted": "pass"
      }
    }
  ],
  "runs": [
    {
      "id": "run-0001",
      "recordId": "rec-01",
      "company": "Bosque Holdings",
      "role": "development associate",
      "lines": [
        {
          "gate": "intake",
          "status": "FAIL",
          "text": "no verbatim requirement text found in posting"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0002",
      "recordId": "rec-02",
      "company": "Frontage Development",
      "role": "right of way agent",
      "lines": [
        {
          "gate": "intake",
          "status": "FAIL",
          "text": "no verbatim requirement text found in posting"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0003",
      "recordId": "rec-03",
      "company": "Escarpment Development",
      "role": "development associate",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "EXPIRED",
          "text": "posting closed since intake"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0004",
      "recordId": "rec-04",
      "company": "Salado Capital",
      "role": "land analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "EXPIRED",
          "text": "posting closed since intake"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0005",
      "recordId": "rec-05",
      "company": "Quarry Land Group",
      "role": "right of way agent",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "BLOCKED",
          "text": "must-have requirement lands on do not have"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0006",
      "recordId": "rec-06",
      "company": "Hardpan Development",
      "role": "land analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "BLOCKED",
          "text": "must-have requirement lands on do not have"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0007",
      "recordId": "rec-07",
      "company": "Meridian Grid Partners",
      "role": "site analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "2 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0008",
      "recordId": "rec-08",
      "company": "Draw Holdings",
      "role": "parcel data lead",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "BLOCKED",
          "text": "no honest answer available"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0009",
      "recordId": "rec-09",
      "company": "Frontage Capital",
      "role": "acquisition analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "2 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0010",
      "recordId": "rec-10",
      "company": "Ridgeline Energy",
      "role": "land analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "1 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0011",
      "recordId": "rec-11",
      "company": "Lometa Land Group",
      "role": "title analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "1 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0012",
      "recordId": "rec-12",
      "company": "Wallow Partners",
      "role": "land analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "ok",
          "text": "2 claims, all labelled a or b"
        },
        {
          "gate": "submitted",
          "status": "ok",
          "text": "2 claims shipped"
        }
      ],
      "exit": 0
    },
    {
      "id": "run-0013",
      "recordId": "rec-13",
      "company": "Ridgeline Development",
      "role": "diligence analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "ok",
          "text": "2 claims, all labelled a or b"
        },
        {
          "gate": "submitted",
          "status": "ok",
          "text": "2 claims shipped"
        }
      ],
      "exit": 0
    },
    {
      "id": "run-0014",
      "recordId": "rec-14",
      "company": "Lometa Development",
      "role": "title analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "ok",
          "text": "2 claims, all labelled a or b"
        },
        {
          "gate": "submitted",
          "status": "ok",
          "text": "2 claims shipped"
        }
      ],
      "exit": 0
    }
  ]
};

export const meta = {
  "pinnedDate": "2026-08-26",
  "posting": {
    "reqId": "MGP-2026-0447",
    "company": "Meridian Grid Partners",
    "role": "site analyst",
    "team": "Origination",
    "reportsTo": "Director of Land",
    "location": "San Antonio, Texas · hybrid, 3 days on site",
    "employment": "full-time",
    "travel": "up to 25%, mostly South Texas",
    "compensation": "$92,000 – $118,000 · bonus eligible",
    "posted": "2026-08-11",
    "closes": "2026-09-08",
    "blurb": "Meridian Grid Partners assembles land positions for utility-scale generation across South Texas. The site analyst supports origination: parcel research, title review and landowner contact ahead of interconnection.",
    "responsibilities": [
      "Research parcels and chains of title ahead of site control.",
      "Pull and reconcile county records across several jurisdictions.",
      "Flag severed mineral estates and other title risk early, in writing.",
      "Prepare landowner contact packets and track every outreach attempt.",
      "Keep the parcel dataset current enough that origination can rely on it."
    ],
    "wildcard": "Tell us about a deal you walked away from, and what it cost you to walk.",
    "subject": "A. Reyes",
    "subjectContact": "San Antonio, Texas · a.reyes@example.invalid · (210) 555-0143",
    "gridOperator": "Sablewood Grid Authority"
  },
  "targets": {
    "records": 14,
    "claimsParsed": 47,
    "claimsCleared": 41,
    "claimsBlocked": 6,
    "sourcesCited": 23
  }
};
