// Generated by scripts/generate.mjs. Do not edit by hand — run: npm run seed
export const sources = [
  {
    "id": "s1",
    "filename": "interview_2026-03-11.txt",
    "kind": "plain text",
    "meta": "transcript · 4,180 words",
    "excerpt": "[00:14:22] Q: How long have you been doing land work?\nA: Fourteen years now. Started in 2012 doing ranch\nsplits out past Hondo, moved into mineral and\nsurface severance work about four years in.\n\n[00:31:07] A: The parcel database is mine. I built it,\nI host it, I run the nightly pull myself.\n\n[00:52:41] Q: Team size on the Atascosa cycle?\nA: Three of us. Me, a title clerk, and a surveyor\non contract."
  },
  {
    "id": "s2",
    "filename": "county_records_export.csv",
    "kind": "csv export",
    "meta": "tabular · 1,284 rows",
    "excerpt": "county,instrument,date,role,acres\nMedina,WD-2024-04188,2024-06-11,buyer_rep,212.4\nFrio,WD-2024-05512,2024-09-02,seller_rep,64.0\nAtascosa,WD-2025-00913,2025-02-20,buyer_rep,341.7\n… 49 more rows matching role filter"
  },
  {
    "id": "s3",
    "filename": "registrar_letter.pdf",
    "kind": "pdf",
    "meta": "document · 1 page",
    "excerpt": "This letter confirms that A. Reyes was awarded the\ndegree of Master of Science in Land Economics,\nconferred 2019-05-18. Degree is in good standing."
  },
  {
    "id": "s4",
    "filename": "repo_manifest.json",
    "kind": "json",
    "meta": "structured · 38 KB",
    "excerpt": "{\n  \"service\": \"parcel-db\",\n  \"host\": \"self\",\n  \"first_commit\": \"2025-11-04\",\n  \"commits\": 412,\n  \"authors\": [\"a.reyes\"]\n}"
  },
  {
    "id": "s5",
    "filename": "call_notes_2026-06-24.pdf",
    "kind": "pdf",
    "meta": "document · 6 pages",
    "excerpt": "Filed 2026-06-24. Reference CALL_NOTES-1771.\nRetained for the parcel file."
  },
  {
    "id": "s6",
    "filename": "permit_index_2025-06-02.csv",
    "kind": "csv export",
    "meta": "tabular · 739 rows",
    "excerpt": "field,value,recorded\npermit_index,211,2025-06-02\n… 137 more rows"
  },
  {
    "id": "s7",
    "filename": "plat_review_2025-11-06.pdf",
    "kind": "pdf",
    "meta": "document · 2 pages",
    "excerpt": "Filed 2025-11-06. Reference PLAT_REVIEW-9135.\nRetained for the parcel file."
  },
  {
    "id": "s8",
    "filename": "closing_file_2026-03-30.pdf",
    "kind": "pdf",
    "meta": "document · 8 pages",
    "excerpt": "Filed 2026-03-30. Reference CLOSING_FILE-1716.\nRetained for the parcel file."
  },
  {
    "id": "s9",
    "filename": "survey_log_2026-03-30.csv",
    "kind": "csv export",
    "meta": "tabular · 1,337 rows",
    "excerpt": "field,value,recorded\nsurvey_log,298,2026-03-30\n… 28 more rows"
  },
  {
    "id": "s10",
    "filename": "tax_roll_2025-07-29.json",
    "kind": "json",
    "meta": "structured · 31 KB",
    "excerpt": "{\n  \"record\": \"tax_roll\",\n  \"recorded\": \"2025-07-29\",\n  \"entries\": 82\n}"
  },
  {
    "id": "s11",
    "filename": "easement_index_2026-06-24.csv",
    "kind": "csv export",
    "meta": "tabular · 2,086 rows",
    "excerpt": "field,value,recorded\neasement_index,693,2026-06-24\n… 80 more rows"
  },
  {
    "id": "s12",
    "filename": "appraisal_notes_2026-03-30.txt",
    "kind": "plain text",
    "meta": "transcript · 1,684 words",
    "excerpt": "Recorded 2026-03-30.\nNotes filed under appraisal_notes. 34 items logged."
  },
  {
    "id": "s13",
    "filename": "title_commitment_2025-09-14.pdf",
    "kind": "pdf",
    "meta": "document · 7 pages",
    "excerpt": "Filed 2025-09-14. Reference TITLE_COMMITMENT-6642.\nRetained for the parcel file."
  },
  {
    "id": "s14",
    "filename": "field_visit_2025-07-29.json",
    "kind": "json",
    "meta": "structured · 28 KB",
    "excerpt": "{\n  \"record\": \"field_visit\",\n  \"recorded\": \"2025-07-29\",\n  \"entries\": 166\n}"
  },
  {
    "id": "s15",
    "filename": "deed_index_2025-07-29.csv",
    "kind": "csv export",
    "meta": "tabular · 409 rows",
    "excerpt": "field,value,recorded\ndeed_index,97,2025-07-29\n… 57 more rows"
  },
  {
    "id": "s16",
    "filename": "escrow_ledger_2025-09-14.pdf",
    "kind": "pdf",
    "meta": "document · 9 pages",
    "excerpt": "Filed 2025-09-14. Reference ESCROW_LEDGER-3566.\nRetained for the parcel file."
  },
  {
    "id": "s17",
    "filename": "zoning_letter_2026-06-24.pdf",
    "kind": "pdf",
    "meta": "document · 2 pages",
    "excerpt": "Filed 2026-06-24. Reference ZONING_LETTER-7968.\nRetained for the parcel file."
  },
  {
    "id": "s18",
    "filename": "well_report_2025-09-14.csv",
    "kind": "csv export",
    "meta": "tabular · 1,612 rows",
    "excerpt": "field,value,recorded\nwell_report,496,2025-09-14\n… 17 more rows"
  },
  {
    "id": "s19",
    "filename": "acreage_audit_2026-01-22.pdf",
    "kind": "pdf",
    "meta": "document · 8 pages",
    "excerpt": "Filed 2026-01-22. Reference ACREAGE_AUDIT-8051.\nRetained for the parcel file."
  },
  {
    "id": "s20",
    "filename": "lease_abstract_2026-03-30.txt",
    "kind": "plain text",
    "meta": "transcript · 5,595 words",
    "excerpt": "Recorded 2026-03-30.\nNotes filed under lease_abstract. 43 items logged."
  },
  {
    "id": "s21",
    "filename": "utility_memo_2025-11-06.pdf",
    "kind": "pdf",
    "meta": "document · 4 pages",
    "excerpt": "Filed 2025-11-06. Reference UTILITY_MEMO-6154.\nRetained for the parcel file."
  },
  {
    "id": "s22",
    "filename": "flood_cert_2026-01-22.json",
    "kind": "json",
    "meta": "structured · 23 KB",
    "excerpt": "{\n  \"record\": \"flood_cert\",\n  \"recorded\": \"2026-01-22\",\n  \"entries\": 9\n}"
  },
  {
    "id": "s23",
    "filename": "boundary_notes_2025-06-02.json",
    "kind": "json",
    "meta": "structured · 82 KB",
    "excerpt": "{\n  \"record\": \"boundary_notes\",\n  \"recorded\": \"2025-06-02\",\n  \"entries\": 39\n}"
  },
  {
    "id": "s0",
    "filename": "— no source —",
    "kind": "none",
    "meta": "nothing on file",
    "excerpt": "No record supports this claim.\n\nText traced to: draft_bio_v3.md (a derived document).\nDerived documents cannot be cited as sources."
  }
];

export const requirements = [
  {
    "id": "r1",
    "title": "Land transaction experience",
    "priority": "must",
    "verbatim": "5+ years originating, negotiating or closing land transactions in Texas. Familiarity with severed mineral estates strongly preferred.",
    "evidence": "interview_2026-03-11.txt at 00:14:22 — fourteen years, starting 2012. county_records_export.csv — 52 closings across three counties.",
    "verdict": "have as documented"
  },
  {
    "id": "r2",
    "title": "Parcel data systems",
    "priority": "must",
    "verbatim": "Comfort building or operating parcel-level data tooling — GIS layers, county record ingestion, or equivalent.",
    "evidence": "repo_manifest.json — parcel-db, self-hosted, 412 commits, sole author. Corroborated by interview_2026-03-11.txt at 00:31:07.",
    "verdict": "have as documented"
  },
  {
    "id": "r3",
    "title": "Interconnection queue familiarity",
    "priority": "preferred",
    "verbatim": "Working knowledge of the Sablewood Grid Authority generation interconnection queue and its study phases is preferred, not required.",
    "evidence": "Nothing on file. A draft asserted fluency here; the assertion traced to draft_bio_v3.md, a derived document, and was blocked at asset lint.",
    "verdict": "do not have"
  },
  {
    "id": "r4",
    "title": "Graduate degree",
    "priority": "preferred",
    "verbatim": "Advanced degree in real estate, economics, land use or a related field.",
    "evidence": "registrar_letter.pdf — M.S. Land Economics, conferred 2019-05-18, in good standing.",
    "verdict": "have as documented"
  },
  {
    "id": "r5",
    "title": "Team leadership",
    "priority": "must",
    "verbatim": "Experience leading a small cross-functional team through a full project cycle.",
    "evidence": "interview_2026-03-11.txt at 00:52:41 — led three people through the Atascosa closing cycle. Cross-functional and a full cycle, but three, not six. The six-person figure has no record behind it.",
    "verdict": "adjacent but honest"
  }
];

export const documents = [
  {
    "id": "cover",
    "label": "cover letter",
    "kind": "letter",
    "blocks": [
      {
        "type": "meta",
        "text": "24 August 2026"
      },
      {
        "type": "meta",
        "text": "Hiring team\nMeridian Grid Partners\nSan Antonio, Texas"
      },
      {
        "type": "para",
        "text": "Dear hiring team,"
      },
      {
        "type": "para",
        "text": "I am writing about the site analyst opening posted on 11 August. I have {{c1}}, most of it on the parcel side of the work the posting describes: assembling positions in country where the surface and the minerals went separate ways decades ago, and where the person who signs is rarely the person on the tax roll."
      },
      {
        "type": "para",
        "text": "The transaction record is the part I would want checked first. County records show {{c2}}, acting for the buyer or the seller, and the instrument numbers are in an export I can send with this letter. Close to a third of those involved a severed mineral estate. That work is slower than a clean fee transfer, and it is the reason I have firm opinions about how long title curative really takes."
      },
      {
        "type": "para",
        "text": "The posting also asks for comfort with parcel-level tooling. I {{c3}} that ingests county records nightly. I run the pull myself and I am its only committer, which is why I can usually answer an acreage or ownership question the same morning it is asked instead of a week later. I also hold an {{c4}}."
      },
      {
        "type": "para",
        "text": "On the interconnection side I bring {{c5}}, and {{c6}} through a full development cycle."
      },
      {
        "type": "para",
        "text": "What I would most want to discuss is where origination currently stalls for you — title curative, landowner contact, or the study phases — because the answer decides which of the above is actually worth anything to you. I am glad to walk through the parcel database on a call and let you push on the data yourself."
      },
      {
        "type": "para",
        "text": "Sincerely,"
      },
      {
        "type": "sig",
        "text": "A. Reyes"
      }
    ],
    "claims": [
      {
        "id": "c1",
        "text": "fourteen years working land transactions in South Texas",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r1"
      },
      {
        "id": "c2",
        "text": "52 closings across Medina, Frio and Atascosa counties",
        "label": "b",
        "sourceId": "s2",
        "requirementId": "r1"
      },
      {
        "id": "c3",
        "text": "built and self-host a parcel database",
        "label": "a",
        "sourceId": "s4",
        "requirementId": "r2"
      },
      {
        "id": "c4",
        "text": "M.S. in Land Economics",
        "label": "b",
        "sourceId": "s3",
        "requirementId": "r4"
      },
      {
        "id": "c5",
        "text": "deep familiarity with the Sablewood interconnection queue",
        "label": "d",
        "sourceId": "s0",
        "requirementId": "r3"
      },
      {
        "id": "c6",
        "text": "a documented record leading a six-person team",
        "label": "c",
        "sourceId": "s0",
        "requirementId": "r5"
      }
    ]
  },
  {
    "id": "resume",
    "label": "résumé",
    "kind": "resume",
    "blocks": [
      {
        "type": "name",
        "text": "A. Reyes"
      },
      {
        "type": "contact",
        "text": "San Antonio, Texas · a.reyes@example.invalid · (210) 555-0143"
      },
      {
        "type": "section",
        "text": "summary"
      },
      {
        "type": "para",
        "text": "{{c1}}, focused on ranch splits and severed mineral estates."
      },
      {
        "type": "section",
        "text": "experience"
      },
      {
        "type": "role",
        "text": "Senior land analyst · Tallow Creek Land Co",
        "meta": "2019 — present"
      },
      {
        "type": "bullet",
        "text": "{{c2}}, acting for the buyer or the seller"
      },
      {
        "type": "bullet",
        "text": "{{c3}} that ingests county records nightly"
      },
      {
        "type": "role",
        "text": "Land analyst · Bitterwater Ranch Company",
        "meta": "2012 — 2019"
      },
      {
        "type": "bullet",
        "text": "Ranch splits, surface and mineral severance work"
      },
      {
        "type": "section",
        "text": "education"
      },
      {
        "type": "bullet",
        "text": "{{c4}}, conferred 2019"
      }
    ],
    "claims": [
      {
        "id": "c1",
        "text": "Fourteen years in Texas land transactions",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r1"
      },
      {
        "id": "c2",
        "text": "52 closings across three counties",
        "label": "b",
        "sourceId": "s2",
        "requirementId": "r1"
      },
      {
        "id": "c3",
        "text": "Built and self-hosted a parcel database",
        "label": "a",
        "sourceId": "s4",
        "requirementId": "r2"
      },
      {
        "id": "c4",
        "text": "M.S. Land Economics",
        "label": "b",
        "sourceId": "s3",
        "requirementId": "r4"
      }
    ]
  },
  {
    "id": "outreach",
    "label": "outreach note",
    "kind": "note",
    "blocks": [
      {
        "type": "meta",
        "text": "to: hiring team, Meridian Grid Partners\nsubject: site analyst opening"
      },
      {
        "type": "para",
        "text": "I saw the site analyst opening. I have {{c1}}, and I {{c2}} — happy to show you what it pulls."
      },
      {
        "type": "para",
        "text": "Worth a short call?"
      },
      {
        "type": "sig",
        "text": "A. Reyes"
      }
    ],
    "claims": [
      {
        "id": "c1",
        "text": "spent fourteen years on Texas land deals",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r1"
      },
      {
        "id": "c2",
        "text": "run my own parcel database",
        "label": "a",
        "sourceId": "s4",
        "requirementId": "r2"
      }
    ]
  }
];

export const gates = {
  "gates": [
    {
      "id": "intake",
      "label": "intake",
      "rejects": "postings with no verbatim requirement text to quote"
    },
    {
      "id": "live",
      "label": "live check",
      "rejects": "postings that have closed or gone stale since intake"
    },
    {
      "id": "pressure",
      "label": "pressure test",
      "rejects": "applications where a must-have requirement lands on do not have"
    },
    {
      "id": "wildcard",
      "label": "wildcard question",
      "rejects": "applications with no honest answer to the open question in the posting"
    },
    {
      "id": "lint",
      "label": "asset lint",
      "rejects": "documents containing a claim labelled c or d"
    },
    {
      "id": "submitted",
      "label": "submitted",
      "rejects": "nothing — a record that reaches this gate has cleared every check"
    }
  ],
  "records": [
    {
      "id": "rec-01",
      "company": "Granite Ranch Group",
      "role": "land analyst",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s5",
        "s18"
      ],
      "stoppedAt": "intake",
      "verdicts": {
        "intake": "fail",
        "live": "not applicable",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-02",
      "company": "Salado Energy",
      "role": "development associate",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s6",
        "s19"
      ],
      "stoppedAt": "intake",
      "verdicts": {
        "intake": "fail",
        "live": "not applicable",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-03",
      "company": "Escarpment Ranch Group",
      "role": "right of way agent",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s7",
        "s20"
      ],
      "stoppedAt": "live",
      "verdicts": {
        "intake": "pass",
        "live": "expired",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-04",
      "company": "Thicket Land Co",
      "role": "parcel data lead",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s4",
        "s8",
        "s21"
      ],
      "stoppedAt": "live",
      "verdicts": {
        "intake": "pass",
        "live": "expired",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-05",
      "company": "Draw Holdings",
      "role": "parcel data lead",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s4",
        "s9",
        "s22"
      ],
      "stoppedAt": "pressure",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "blocked",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-06",
      "company": "Frontage Capital",
      "role": "acquisition analyst",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s3",
        "s10",
        "s23"
      ],
      "stoppedAt": "pressure",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "blocked",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-07",
      "company": "Meridian Grid Partners",
      "role": "site analyst",
      "focus": true,
      "claimsParsed": 12,
      "claimsCleared": 10,
      "claimsBlocked": 2,
      "sourceIds": [
        "s1",
        "s2",
        "s4",
        "s3"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-08",
      "company": "Ridgeline Energy",
      "role": "land analyst",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s1",
        "s11"
      ],
      "stoppedAt": "wildcard",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "blocked",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-09",
      "company": "Lometa Land Group",
      "role": "title analyst",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 1,
      "claimsBlocked": 2,
      "sourceIds": [
        "s12"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-10",
      "company": "Wallow Partners",
      "role": "land analyst",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 1,
      "claimsBlocked": 1,
      "sourceIds": [
        "s4",
        "s13"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-11",
      "company": "Ridgeline Development",
      "role": "diligence analyst",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 2,
      "claimsBlocked": 1,
      "sourceIds": [
        "s14"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-12",
      "company": "Lometa Development",
      "role": "title analyst",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s1",
        "s15"
      ],
      "stoppedAt": null,
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "pass",
        "submitted": "pass"
      }
    },
    {
      "id": "rec-13",
      "company": "Escarpment Energy",
      "role": "land analyst",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s1",
        "s16"
      ],
      "stoppedAt": null,
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "pass",
        "submitted": "pass"
      }
    },
    {
      "id": "rec-14",
      "company": "Caliche Land Co",
      "role": "title analyst",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s17"
      ],
      "stoppedAt": null,
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "pass",
        "submitted": "pass"
      }
    }
  ],
  "runs": [
    {
      "id": "run-0001",
      "recordId": "rec-01",
      "company": "Granite Ranch Group",
      "role": "land analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "FAIL",
          "text": "no verbatim requirement text found in posting"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0002",
      "recordId": "rec-02",
      "company": "Salado Energy",
      "role": "development associate",
      "lines": [
        {
          "gate": "intake",
          "status": "FAIL",
          "text": "no verbatim requirement text found in posting"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0003",
      "recordId": "rec-03",
      "company": "Escarpment Ranch Group",
      "role": "right of way agent",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "EXPIRED",
          "text": "posting closed since intake"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0004",
      "recordId": "rec-04",
      "company": "Thicket Land Co",
      "role": "parcel data lead",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "EXPIRED",
          "text": "posting closed since intake"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0005",
      "recordId": "rec-05",
      "company": "Draw Holdings",
      "role": "parcel data lead",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "BLOCKED",
          "text": "must-have requirement lands on do not have"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0006",
      "recordId": "rec-06",
      "company": "Frontage Capital",
      "role": "acquisition analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "BLOCKED",
          "text": "must-have requirement lands on do not have"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0007",
      "recordId": "rec-07",
      "company": "Meridian Grid Partners",
      "role": "site analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "2 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0008",
      "recordId": "rec-08",
      "company": "Ridgeline Energy",
      "role": "land analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "BLOCKED",
          "text": "no honest answer available"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0009",
      "recordId": "rec-09",
      "company": "Lometa Land Group",
      "role": "title analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "2 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0010",
      "recordId": "rec-10",
      "company": "Wallow Partners",
      "role": "land analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "1 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0011",
      "recordId": "rec-11",
      "company": "Ridgeline Development",
      "role": "diligence analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "1 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0012",
      "recordId": "rec-12",
      "company": "Lometa Development",
      "role": "title analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "ok",
          "text": "3 claims, all labelled a or b"
        },
        {
          "gate": "submitted",
          "status": "ok",
          "text": "3 claims shipped"
        }
      ],
      "exit": 0
    },
    {
      "id": "run-0013",
      "recordId": "rec-13",
      "company": "Escarpment Energy",
      "role": "land analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "ok",
          "text": "2 claims, all labelled a or b"
        },
        {
          "gate": "submitted",
          "status": "ok",
          "text": "2 claims shipped"
        }
      ],
      "exit": 0
    },
    {
      "id": "run-0014",
      "recordId": "rec-14",
      "company": "Caliche Land Co",
      "role": "title analyst",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "ok",
          "text": "2 claims, all labelled a or b"
        },
        {
          "gate": "submitted",
          "status": "ok",
          "text": "2 claims shipped"
        }
      ],
      "exit": 0
    }
  ]
};

export const meta = {
  "pinnedDate": "2026-08-26",
  "posting": {
    "company": "Meridian Grid Partners",
    "role": "site analyst",
    "location": "San Antonio, Texas · hybrid",
    "posted": "2026-08-11",
    "blurb": "Meridian Grid Partners assembles land positions for utility-scale generation across South Texas. The site analyst supports origination: parcel research, title review and landowner contact ahead of interconnection.",
    "subject": "A. Reyes",
    "subjectContact": "San Antonio, Texas · a.reyes@example.invalid · (210) 555-0143",
    "gridOperator": "Sablewood Grid Authority"
  },
  "targets": {
    "records": 14,
    "claimsParsed": 47,
    "claimsCleared": 41,
    "claimsBlocked": 6,
    "sourcesCited": 23
  }
};
