// Generated by scripts/generate.mjs. Do not edit by hand — run: npm run seed
export const sources = [
  {
    "id": "s1",
    "filename": "intake-interview-2026-03-11.txt",
    "kind": "plain text",
    "category": "self-report",
    "meta": "interview transcript · 3,940 words",
    "excerpt": "[00:09:40] Q: How long have you been on equipment?\nA: Eleven years. Two in the shop starting out, nine\nin the field since. Dozers, excavators, wheel loaders,\nsome ag equipment.\n\n[00:22:15] A: I rebuild final drives and hydrostatic\npumps. Learned it in the apprenticeship and never\nstopped doing it.\n\n[00:41:03] Q: Have you run a crew?\nA: Two techs plus me, through one rebuild season.\nNot a big crew. I was the one signing the work off."
  },
  {
    "id": "s2",
    "filename": "work-orders-2023-2026.csv",
    "kind": "csv export",
    "category": "system export",
    "meta": "work order export · 1,284 rows",
    "excerpt": "work_order,date,machine,fault_system,site,hours,comeback\nWO-88214,2024-03-11,excavator,hydraulic,customer,6.5,false\nWO-91077,2024-07-02,dozer,electrical,customer,4.0,false\nWO-94663,2025-01-19,wheel_loader,hydraulic,customer,9.5,true\n… 409 more rows where site = customer\n\n-- 412 rows with site = customer\n-- 63 of those with fault_system = hydraulic\n-- 10 with comeback = true  (2.4%)"
  },
  {
    "id": "s3",
    "filename": "training-record-2024.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "training centre record · 2 pages",
    "excerpt": "Service training record\n\nTechnician   D. Marek\nProgramme    Field service, four stage\n\nStage 1  hydraulics           completed 2022-05-06\nStage 2  electrical systems   completed 2022-11-18\nStage 3  powertrain           completed 2023-08-24\nStage 4  diagnostics          completed 2024-04-12\n\nIssued by the training centre, not by the technician."
  },
  {
    "id": "s4",
    "filename": "licence-and-endorsements.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "licensing record · 1 page",
    "excerpt": "Commercial driver licence — record of endorsements\n\nHolder        D. Marek\nClass         A\nEndorsements  tanker, air brakes — no restriction\nIssued        2016-02-11\nStatus        active, no suspensions on file"
  },
  {
    "id": "s5",
    "filename": "performance-review-2026-02-09.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 9 pages",
    "excerpt": "Reference PERFORMANCEREVIEW-6327\nIssued 2026-02-09.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s6",
    "filename": "employment-verification-2025-04-18.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 4 pages",
    "excerpt": "Reference EMPLOYMENTVERIFICATION-2469\nIssued 2025-04-18.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s7",
    "filename": "reference-letter-2025-07-29.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 2 pages",
    "excerpt": "Reference REFERENCELETTER-6463\nIssued 2025-07-29.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s8",
    "filename": "apprenticeship-record-2026-03-30.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 4 pages",
    "excerpt": "Reference APPRENTICESHIPRECORD-2872\nIssued 2026-03-30.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s9",
    "filename": "safety-training-card-2026-06-24.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 5 pages",
    "excerpt": "Reference SAFETYTRAININGCARD-7802\nIssued 2026-06-24.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s10",
    "filename": "respirator-fit-test-2026-05-11.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 1 pages",
    "excerpt": "Reference RESPIRATORFITTEST-3297\nIssued 2026-05-11.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s11",
    "filename": "medical-examiner-card-2026-03-30.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 6 pages",
    "excerpt": "Reference MEDICALEXAMINERCARD-3645\nIssued 2026-03-30.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s12",
    "filename": "background-check-clearance-2025-04-18.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 8 pages",
    "excerpt": "Reference BACKGROUNDCHECKCLEARANCE-3598\nIssued 2025-04-18.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s13",
    "filename": "customer-survey-results-2025-09-14.csv",
    "kind": "csv export",
    "category": "third-party record",
    "meta": "export · 481 rows",
    "excerpt": "issued_on,item,units,verified\n2025-09-14,customer_survey_results,45,true\n… 87 more rows\n\n-- issued by the awarding body, not by the subject"
  },
  {
    "id": "s14",
    "filename": "award-letter-2026-02-09.pdf",
    "kind": "pdf",
    "category": "third-party record",
    "meta": "issued · 3 pages",
    "excerpt": "Reference AWARDLETTER-2469\nIssued 2026-02-09.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them."
  },
  {
    "id": "s15",
    "filename": "torque-wrench-calibration-2026-03-30.csv",
    "kind": "csv export",
    "category": "system export",
    "meta": "export · 347 rows",
    "excerpt": "exported_on,torque_wrench_calibration,count\n2026-03-30,total,605\n2026-03-30,flagged,13\n… 171 more rows\n\n-- generated by the system, not typed by hand"
  },
  {
    "id": "s16",
    "filename": "tool-inventory-2026-02-09.csv",
    "kind": "csv export",
    "category": "system export",
    "meta": "export · 2,126 rows",
    "excerpt": "exported_on,tool_inventory,count\n2026-02-09,total,316\n2026-02-09,flagged,14\n… 72 more rows\n\n-- generated by the system, not typed by hand"
  },
  {
    "id": "s17",
    "filename": "mileage-log-2025-07-29.csv",
    "kind": "csv export",
    "category": "system export",
    "meta": "export · 409 rows",
    "excerpt": "exported_on,mileage_log,count\n2025-07-29,total,221\n2025-07-29,flagged,25\n… 87 more rows\n\n-- generated by the system, not typed by hand"
  },
  {
    "id": "s18",
    "filename": "timesheet-export-2026-06-24.csv",
    "kind": "csv export",
    "category": "system export",
    "meta": "export · 721 rows",
    "excerpt": "exported_on,timesheet_export,count\n2026-06-24,total,964\n2026-06-24,flagged,6\n… 171 more rows\n\n-- generated by the system, not typed by hand"
  },
  {
    "id": "s19",
    "filename": "warranty-claim-log-2025-09-14.csv",
    "kind": "csv export",
    "category": "system export",
    "meta": "export · 763 rows",
    "excerpt": "exported_on,warranty_claim_log,count\n2025-09-14,total,496\n2025-09-14,flagged,1\n… 129 more rows\n\n-- generated by the system, not typed by hand"
  },
  {
    "id": "s20",
    "filename": "parts-usage-export-2026-01-22.csv",
    "kind": "csv export",
    "category": "system export",
    "meta": "export · 1,965 rows",
    "excerpt": "exported_on,parts_usage_export,count\n2026-01-22,total,220\n2026-01-22,flagged,28\n… 203 more rows\n\n-- generated by the system, not typed by hand"
  },
  {
    "id": "s21",
    "filename": "fault-code-notebook-2026-06-24.txt",
    "kind": "plain text",
    "category": "self-report",
    "meta": "own notes · 3,230 words",
    "excerpt": "Written 2026-06-24.\n\n21 entries, kept by the subject for their own\nreference. Useful for recall. Not evidence on its\nown — nothing here was checked by anyone else."
  },
  {
    "id": "s22",
    "filename": "machine-notes-2026-01-22.txt",
    "kind": "plain text",
    "category": "self-report",
    "meta": "own notes · 4,557 words",
    "excerpt": "Written 2026-01-22.\n\n14 entries, kept by the subject for their own\nreference. Useful for recall. Not evidence on its\nown — nothing here was checked by anyone else."
  },
  {
    "id": "s23",
    "filename": "career-questionnaire-2025-04-18.txt",
    "kind": "plain text",
    "category": "self-report",
    "meta": "own notes · 5,193 words",
    "excerpt": "Written 2025-04-18.\n\n46 entries, kept by the subject for their own\nreference. Useful for recall. Not evidence on its\nown — nothing here was checked by anyone else."
  },
  {
    "id": "s0",
    "filename": "— no record —",
    "kind": "none",
    "category": "none",
    "meta": "nothing in the library",
    "excerpt": "No record in the library supports this claim.\n\nText traced to: resume-2025-draft.docx\n\nThat file is an earlier document this pipeline wrote.\nA derived document cannot be cited as a source —\nciting it would mean the system vouching for itself."
  }
];

export const requirements = [
  {
    "id": "r1",
    "title": "Field diagnostic experience",
    "priority": "must",
    "verbatim": "3+ years diagnosing and repairing heavy equipment in the field, not only in a shop bay. Hydraulic and electrical fault finding required.",
    "evidence": "intake-interview-2026-03-11.txt at 00:09:40 — eleven years, nine of them in the field. work-orders-2023-2026.csv — 412 work orders closed on customer sites, 63 of them hydraulic, 10 comebacks.",
    "verdict": "have as documented"
  },
  {
    "id": "r2",
    "title": "Manufacturer service training",
    "priority": "must",
    "verbatim": "Current manufacturer service training for at least one major equipment line, or an equivalent apprenticeship completed.",
    "evidence": "training-record-2024.pdf — four-stage field service programme, final stage completed 2024-04-12, issued by the training centre. Rebuild work described by the subject at 00:22:15.",
    "verdict": "have as documented"
  },
  {
    "id": "r3",
    "title": "Crane and rigging certification",
    "priority": "preferred",
    "verbatim": "Crane and rigging certification preferred. Technician may set and pull components without a dedicated lift crew.",
    "evidence": "Nothing in the library. A draft claimed the certification; the claim traced to resume-2025-draft.docx, a document this pipeline wrote, and was blocked at asset lint. No certificate, no card, no issuing body.",
    "verdict": "do not have"
  },
  {
    "id": "r4",
    "title": "Commercial driver licence",
    "priority": "preferred",
    "verbatim": "Class A commercial driver licence preferred. Technician will move a service truck and equipment trailer.",
    "evidence": "licence-and-endorsements.pdf — class A, tanker and air brake endorsements, active, no suspensions on file.",
    "verdict": "have as documented"
  },
  {
    "id": "r5",
    "title": "Crew leadership",
    "priority": "must",
    "verbatim": "Experience leading a small crew through a full job cycle, including sign-off on other technicians' work.",
    "evidence": "intake-interview-2026-03-11.txt at 00:41:03 — led two technicians through one rebuild season and signed the work off. A crew and a full cycle, but two, not six, and self-reported. The six-technician figure has no record behind it at all.",
    "verdict": "adjacent but honest"
  }
];

export const documents = [
  {
    "id": "cover",
    "label": "cover letter",
    "kind": "letter",
    "blocks": [
      {
        "type": "meta",
        "text": "24 August 2026"
      },
      {
        "type": "meta",
        "text": "Service manager\nIronline Machinery Company\nSan Antonio, Texas"
      },
      {
        "type": "para",
        "text": "Dear service manager,"
      },
      {
        "type": "para",
        "text": "I am applying for the field service technician opening posted on 11 August. I have {{c1}}, and the work order export from my current employer shows {{c2}}, {{c7}}."
      },
      {
        "type": "para",
        "text": "Most of the job is diagnosis. A machine is down on a site, the operator has a theory, and the fault code is pointing somewhere else again. I work through the hydraulics and the electrical until the machine tells me what is actually wrong, fix it to spec, and write it up so the next technician does not start from nothing. I finished {{c3}}, and I have {{c8}} since my apprenticeship."
      },
      {
        "type": "para",
        "text": "I hold {{c4}}, so I can move the truck and the trailer without waiting on anyone. I take the on-call rotation seriously. Nights and weekends in season are the job, and the customer who calls at four in the morning is the one who remembers how you answered."
      },
      {
        "type": "para",
        "text": "I also bring {{c5}}, and {{c6}} through a full season."
      },
      {
        "type": "para",
        "text": "I would rather show you than tell you. Put me on a machine that has been looked at twice already and let me work it. If the diagnosis is wrong you will know inside a day, which is the point."
      },
      {
        "type": "para",
        "text": "Sincerely,"
      },
      {
        "type": "sig",
        "text": "D. Marek"
      }
    ],
    "claims": [
      {
        "id": "c1",
        "text": "eleven years on heavy equipment, nine of them in the field",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r1"
      },
      {
        "id": "c2",
        "text": "412 work orders closed on customer sites",
        "label": "b",
        "sourceId": "s2",
        "requirementId": "r1"
      },
      {
        "id": "c7",
        "text": "63 of them hydraulic faults found and repaired on site",
        "label": "b",
        "sourceId": "s2",
        "requirementId": "r1"
      },
      {
        "id": "c3",
        "text": "the four-stage manufacturer service training",
        "label": "b",
        "sourceId": "s3",
        "requirementId": "r2"
      },
      {
        "id": "c8",
        "text": "rebuilt final drives and hydrostatic pumps",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r2"
      },
      {
        "id": "c4",
        "text": "a class A licence with tanker and air brake endorsements",
        "label": "b",
        "sourceId": "s4",
        "requirementId": "r4"
      },
      {
        "id": "c5",
        "text": "a current crane and rigging certification",
        "label": "d",
        "sourceId": "s0",
        "requirementId": "r3"
      },
      {
        "id": "c6",
        "text": "a documented record leading a six-technician crew",
        "label": "c",
        "sourceId": "s0",
        "requirementId": "r5"
      }
    ]
  },
  {
    "id": "resume",
    "label": "résumé",
    "kind": "resume",
    "blocks": [
      {
        "type": "name",
        "text": "D. Marek"
      },
      {
        "type": "contact",
        "text": "San Antonio, Texas · d.marek@example.invalid · (210) 555-0176"
      },
      {
        "type": "section",
        "text": "summary"
      },
      {
        "type": "para",
        "text": "{{c1}}. Field diagnosis on hydraulics, electrical and powertrain, repaired to spec and written up so the next technician can follow it."
      },
      {
        "type": "section",
        "text": "experience"
      },
      {
        "type": "role",
        "text": "Field service technician · Redgate Equipment Company",
        "meta": "2019 — present"
      },
      {
        "type": "bullet",
        "text": "{{c2}} across three service territories"
      },
      {
        "type": "bullet",
        "text": "{{c7}}, without pulling the machine to the shop"
      },
      {
        "type": "bullet",
        "text": "{{c6}} across three years of closed work orders"
      },
      {
        "type": "bullet",
        "text": "{{c8}} — two technicians and myself"
      },
      {
        "type": "role",
        "text": "Heavy equipment technician · Millrace Machine Works",
        "meta": "2015 — 2019"
      },
      {
        "type": "bullet",
        "text": "{{c5}}, plus undercarriage and track work"
      },
      {
        "type": "bullet",
        "text": "Shop diagnosis on dozers, excavators and wheel loaders"
      },
      {
        "type": "bullet",
        "text": "Wrote the hydrostatic fault notes the shop still works from"
      },
      {
        "type": "role",
        "text": "Apprentice technician · Longspur Equipment",
        "meta": "2013 — 2015"
      },
      {
        "type": "bullet",
        "text": "Two-year apprenticeship completed under a master technician"
      },
      {
        "type": "bullet",
        "text": "Preventive maintenance, fluid analysis, undercarriage measurement"
      },
      {
        "type": "section",
        "text": "training and licences"
      },
      {
        "type": "bullet",
        "text": "{{c3}}, final stage completed 2024"
      },
      {
        "type": "bullet",
        "text": "{{c4}}"
      },
      {
        "type": "bullet",
        "text": "Safety training card, current"
      },
      {
        "type": "section",
        "text": "tools"
      },
      {
        "type": "bullet",
        "text": "Own hand and torque tooling, calibration current"
      },
      {
        "type": "bullet",
        "text": "Laptop diagnostics, fault code reading, hydraulic pressure testing"
      }
    ],
    "claims": [
      {
        "id": "c1",
        "text": "Eleven years on heavy equipment, nine in the field",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r1"
      },
      {
        "id": "c2",
        "text": "412 work orders closed on customer sites",
        "label": "b",
        "sourceId": "s2",
        "requirementId": "r1"
      },
      {
        "id": "c7",
        "text": "63 hydraulic faults diagnosed and repaired on site",
        "label": "b",
        "sourceId": "s2",
        "requirementId": "r1"
      },
      {
        "id": "c6",
        "text": "A 2.4% comeback rate",
        "label": "b",
        "sourceId": "s2",
        "requirementId": "r1"
      },
      {
        "id": "c8",
        "text": "Led a crew through a full rebuild season",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r5"
      },
      {
        "id": "c5",
        "text": "Final drive and hydrostatic pump rebuilds",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r2"
      },
      {
        "id": "c3",
        "text": "Four-stage manufacturer service training",
        "label": "b",
        "sourceId": "s3",
        "requirementId": "r2"
      },
      {
        "id": "c4",
        "text": "Class A licence · tanker and air brake endorsements",
        "label": "b",
        "sourceId": "s4",
        "requirementId": "r4"
      }
    ]
  },
  {
    "id": "outreach",
    "label": "outreach note",
    "kind": "note",
    "blocks": [
      {
        "type": "meta",
        "text": "to: service manager, Ironline Machinery Company\nsubject: field service technician opening"
      },
      {
        "type": "para",
        "text": "I saw the field service technician opening. I have {{c1}}, and I {{c2}} — happy to bring my own tools and work a machine that has already been looked at twice."
      },
      {
        "type": "para",
        "text": "Worth a call?"
      },
      {
        "type": "sig",
        "text": "D. Marek"
      }
    ],
    "claims": [
      {
        "id": "c1",
        "text": "spent nine years fixing machines on customer sites",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r1"
      },
      {
        "id": "c2",
        "text": "rebuild final drives and hydrostatic pumps",
        "label": "a",
        "sourceId": "s1",
        "requirementId": "r2"
      }
    ]
  }
];

export const gates = {
  "gates": [
    {
      "id": "intake",
      "label": "intake",
      "rejects": "postings with no verbatim requirement text to quote",
      "plain": "Reads the posting and pulls out what it asks for, word for word."
    },
    {
      "id": "live",
      "label": "live check",
      "rejects": "postings that have closed or gone stale since intake",
      "plain": "Checks the job is still open before any work goes into it."
    },
    {
      "id": "pressure",
      "label": "pressure test",
      "rejects": "applications where a must-have requirement lands on do not have",
      "plain": "Asks honestly whether this person can do the job, requirement by requirement."
    },
    {
      "id": "wildcard",
      "label": "wildcard question",
      "rejects": "applications with no honest answer to the open question in the posting",
      "plain": "Works out an honest answer to the odd question the posting asks."
    },
    {
      "id": "lint",
      "label": "asset lint",
      "rejects": "documents containing a claim labelled c or d",
      "plain": "Reads the finished documents and checks every claim has a record behind it."
    },
    {
      "id": "submitted",
      "label": "submitted",
      "rejects": "nothing — a record that reaches this gate has cleared every check",
      "plain": "The application goes out."
    }
  ],
  "records": [
    {
      "id": "rec-01",
      "company": "Pike Rental",
      "role": "undercarriage technician",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s5",
        "s18"
      ],
      "stoppedAt": "intake",
      "verdicts": {
        "intake": "fail",
        "live": "not applicable",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-02",
      "company": "Sledge Service Group",
      "role": "undercarriage technician",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s3",
        "s6",
        "s19"
      ],
      "stoppedAt": "intake",
      "verdicts": {
        "intake": "fail",
        "live": "not applicable",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-03",
      "company": "Drayline Heavy Equipment",
      "role": "equipment inspector",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s7",
        "s20"
      ],
      "stoppedAt": "live",
      "verdicts": {
        "intake": "pass",
        "live": "expired",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-04",
      "company": "Tandem Rental",
      "role": "powertrain technician",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s3",
        "s8",
        "s21"
      ],
      "stoppedAt": "live",
      "verdicts": {
        "intake": "pass",
        "live": "expired",
        "pressure": "not applicable",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-05",
      "company": "Cinder Equipment Co",
      "role": "powertrain technician",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s3",
        "s9",
        "s22"
      ],
      "stoppedAt": "pressure",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "blocked",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-06",
      "company": "Flint Diesel",
      "role": "diesel technician",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 3,
      "claimsBlocked": 0,
      "sourceIds": [
        "s4",
        "s10",
        "s23"
      ],
      "stoppedAt": "pressure",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "blocked",
        "wildcard": "not applicable",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-07",
      "company": "Ironline Machinery Company",
      "role": "field service technician",
      "focus": true,
      "claimsParsed": 18,
      "claimsCleared": 16,
      "claimsBlocked": 2,
      "sourceIds": [
        "s1",
        "s2",
        "s3",
        "s4"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-08",
      "company": "Ridgeline Service Group",
      "role": "shop technician",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s1",
        "s11"
      ],
      "stoppedAt": "wildcard",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "blocked",
        "lint": "not applicable",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-09",
      "company": "Keystone Machinery",
      "role": "hydraulics specialist",
      "focus": false,
      "claimsParsed": 3,
      "claimsCleared": 1,
      "claimsBlocked": 2,
      "sourceIds": [
        "s12"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-10",
      "company": "Wallow Machine Works",
      "role": "shop technician",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 1,
      "claimsBlocked": 1,
      "sourceIds": [
        "s3",
        "s13"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-11",
      "company": "Ridgeline Power Systems",
      "role": "service writer",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 1,
      "claimsBlocked": 1,
      "sourceIds": [
        "s14"
      ],
      "stoppedAt": "lint",
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "blocked",
        "submitted": "not applicable"
      }
    },
    {
      "id": "rec-12",
      "company": "Keystone Power Systems",
      "role": "hydraulics specialist",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s1",
        "s15"
      ],
      "stoppedAt": null,
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "pass",
        "submitted": "pass"
      }
    },
    {
      "id": "rec-13",
      "company": "Drayline Service Group",
      "role": "shop technician",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s1",
        "s16"
      ],
      "stoppedAt": null,
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "pass",
        "submitted": "pass"
      }
    },
    {
      "id": "rec-14",
      "company": "Blackjack Rental",
      "role": "hydraulics specialist",
      "focus": false,
      "claimsParsed": 2,
      "claimsCleared": 2,
      "claimsBlocked": 0,
      "sourceIds": [
        "s17"
      ],
      "stoppedAt": null,
      "verdicts": {
        "intake": "pass",
        "live": "pass",
        "pressure": "pass",
        "wildcard": "pass",
        "lint": "pass",
        "submitted": "pass"
      }
    }
  ],
  "runs": [
    {
      "id": "run-0001",
      "recordId": "rec-01",
      "company": "Pike Rental",
      "role": "undercarriage technician",
      "lines": [
        {
          "gate": "intake",
          "status": "FAIL",
          "text": "no verbatim requirement text found in posting"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0002",
      "recordId": "rec-02",
      "company": "Sledge Service Group",
      "role": "undercarriage technician",
      "lines": [
        {
          "gate": "intake",
          "status": "FAIL",
          "text": "no verbatim requirement text found in posting"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0003",
      "recordId": "rec-03",
      "company": "Drayline Heavy Equipment",
      "role": "equipment inspector",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "EXPIRED",
          "text": "posting closed since intake"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0004",
      "recordId": "rec-04",
      "company": "Tandem Rental",
      "role": "powertrain technician",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "EXPIRED",
          "text": "posting closed since intake"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0005",
      "recordId": "rec-05",
      "company": "Cinder Equipment Co",
      "role": "powertrain technician",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "BLOCKED",
          "text": "must-have requirement lands on do not have"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0006",
      "recordId": "rec-06",
      "company": "Flint Diesel",
      "role": "diesel technician",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "BLOCKED",
          "text": "must-have requirement lands on do not have"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0007",
      "recordId": "rec-07",
      "company": "Ironline Machinery Company",
      "role": "field service technician",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "2 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0008",
      "recordId": "rec-08",
      "company": "Ridgeline Service Group",
      "role": "shop technician",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "BLOCKED",
          "text": "no honest answer available"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0009",
      "recordId": "rec-09",
      "company": "Keystone Machinery",
      "role": "hydraulics specialist",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "2 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0010",
      "recordId": "rec-10",
      "company": "Wallow Machine Works",
      "role": "shop technician",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "1 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0011",
      "recordId": "rec-11",
      "company": "Ridgeline Power Systems",
      "role": "service writer",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "BLOCKED",
          "text": "1 claim(s) labelled c or d"
        }
      ],
      "exit": 1
    },
    {
      "id": "run-0012",
      "recordId": "rec-12",
      "company": "Keystone Power Systems",
      "role": "hydraulics specialist",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "ok",
          "text": "2 claims, all labelled a or b"
        },
        {
          "gate": "submitted",
          "status": "ok",
          "text": "2 claims shipped"
        }
      ],
      "exit": 0
    },
    {
      "id": "run-0013",
      "recordId": "rec-13",
      "company": "Drayline Service Group",
      "role": "shop technician",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "ok",
          "text": "2 claims, all labelled a or b"
        },
        {
          "gate": "submitted",
          "status": "ok",
          "text": "2 claims shipped"
        }
      ],
      "exit": 0
    },
    {
      "id": "run-0014",
      "recordId": "rec-14",
      "company": "Blackjack Rental",
      "role": "hydraulics specialist",
      "lines": [
        {
          "gate": "intake",
          "status": "ok",
          "text": "5 requirements quoted verbatim"
        },
        {
          "gate": "live",
          "status": "ok",
          "text": "posting live, rechecked 2026-08-26"
        },
        {
          "gate": "pressure",
          "status": "ok",
          "text": "stretch — 1 must-have adjacent but honest"
        },
        {
          "gate": "wildcard",
          "status": "ok",
          "text": "answer drafted from interview_2026-03-11.txt"
        },
        {
          "gate": "lint",
          "status": "ok",
          "text": "2 claims, all labelled a or b"
        },
        {
          "gate": "submitted",
          "status": "ok",
          "text": "2 claims shipped"
        }
      ],
      "exit": 0
    }
  ]
};

export const meta = {
  "pinnedDate": "2026-08-26",
  "posting": {
    "reqId": "IMC-2026-0318",
    "company": "Ironline Machinery Company",
    "role": "field service technician",
    "team": "Product Support",
    "reportsTo": "Service Manager, South Territory",
    "location": "San Antonio, Texas · field based, South Texas territory",
    "employment": "full-time · on-call rotation",
    "travel": "daily to customer sites, up to 150 miles",
    "compensation": "$31.50 – $41.75 per hour · overtime after 40 · tool allowance",
    "posted": "2026-08-11",
    "closes": "2026-09-08",
    "blurb": "Ironline Machinery sells, rents and services heavy equipment across South Texas. Field service technicians work on the customer's site, in whatever the machine is sitting in, and they are the company's reputation on the day something breaks.",
    "responsibilities": [
      "Diagnose hydraulic, electrical and powertrain faults on customer sites.",
      "Repair to the manufacturer procedure and torque spec, first time where possible.",
      "Write a service report the next technician can actually follow.",
      "Keep the truck, the tooling and the calibrated instruments in order.",
      "Take the on-call rotation, including nights and weekends in season.",
      "Work safely in the conditions the machine is in, not the conditions you would prefer."
    ],
    "wildcard": "Tell us about a repair you signed off on that came back. What did you miss?",
    "subject": "D. Marek",
    "subjectContact": "San Antonio, Texas · d.marek@example.invalid · (210) 555-0176",
    "physical": "Lifting to 80 lb, climbing, cramped spaces, outdoor conditions year round"
  },
  "targets": {
    "records": 14,
    "claimsParsed": 47,
    "claimsCleared": 41,
    "claimsBlocked": 6,
    "sourcesCited": 23
  }
};
