// Seed generator for the provenance demo.
//
// Reads data/seed.config.json and writes:
//   data/generated/sources.json
//   data/generated/requirements.json
//   data/generated/documents.json
//   data/generated/gates.json
//   src/js/data.js            (the same objects as an ES module, so the page never fetches)
//
// Determinism is a hard requirement: a fixed seed must produce byte-identical output.
// There is no Date.now(), no Math.random(), no locale-dependent formatting anywhere below.
// Every number the page shows is derived from this output and re-asserted at the bottom.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const config = JSON.parse(readFileSync(join(ROOT, 'data/seed.config.json'), 'utf8'));

/* ---------------------------------------------------------------- prng --- */

// mulberry32: small, fast, and stable across Node versions.
function makeRandom(seed) {
  let a = seed >>> 0;
  return function random() {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const random = makeRandom(config.seed);
const pick = (list) => list[Math.floor(random() * list.length)];
const between = (lo, hi) => lo + Math.floor(random() * (hi - lo + 1));

// Thousands separators by hand. Intl output depends on the ICU build Node was compiled with,
// which would make the seed output machine-dependent.
const grouped = (n) => String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');

/* ------------------------------------------------------------- sources --- */

const EXTENSION = {
  'plain text': '.txt',
  'csv export': '.csv',
  pdf: '.pdf',
};

// The library is a person's own store of career records, so the metadata reads the way such a
// folder actually reads: who issued the thing, and how much of it there is.
function generatedMeta(kind, category) {
  if (kind === 'pdf') {
    const issuer = category === 'third-party record' ? 'issued' : 'filed';
    return `${issuer} · ${between(1, 9)} pages`;
  }
  if (kind === 'csv export') return `export · ${grouped(between(87, 2310))} rows`;
  if (category === 'self-report') return `own notes · ${grouped(between(310, 5940))} words`;
  return `record · ${grouped(between(310, 5940))} words`;
}

function generatedExcerpt(topic, stamp) {
  const { name, category, kind } = topic;
  const reference = `${name.toUpperCase().replace(/-/g, '')}-${between(1004, 9987)}`;

  if (category === 'third-party record') {
    if (kind === 'csv export') {
      return `issued_on,item,units,verified\n${stamp},${name.replace(/-/g, '_')},${between(3, 47)},true\n… ${between(4, 96)} more rows\n\n-- issued by the awarding body, not by the subject`;
    }
    return `Reference ${reference}\nIssued ${stamp}.\n\nThis document was produced by a third party and\nretained by the subject. It attests to the items\nlisted above and nothing beyond them.`;
  }

  if (category === 'system export') {
    return `exported_on,${name.replace(/-/g, '_')},count\n${stamp},total,${between(11, 989)}\n${stamp},flagged,${between(1, 37)}\n… ${between(13, 217)} more rows\n\n-- generated by the system, not typed by hand`;
  }

  return `Written ${stamp}.\n\n${between(3, 47)} entries, kept by the subject for their own\nreference. Useful for recall. Not evidence on its\nown — nothing here was checked by anyone else.`;
}

// Four authored records, then one generated record per topic in the library.
// The pool size must equal corpusTargets.sourcesCited.
const sources = [...config.sources.map((s) => ({ ...s }))];
config.sourceWords.topic.forEach((topic) => {
  const stamp = pick(config.sourceWords.stamp);
  sources.push({
    id: `s${sources.length + 1}`,
    filename: `${topic.name}-${stamp}${EXTENSION[topic.kind]}`,
    kind: topic.kind,
    category: topic.category,
    meta: generatedMeta(topic.kind, topic.category),
    excerpt: generatedExcerpt(topic, stamp),
  });
});
// The null source sorts last: it is not a record, it is the absence of one.
sources.push({ ...config.nullSource });

const realSourceIds = sources.filter((s) => s.id !== 's0').map((s) => s.id);

/* -------------------------------------------------- requirements + docs --- */

const requirements = config.requirements.map((r) => ({ ...r }));

const documents = config.documents.map((d) => ({
  id: d.id,
  label: d.label,
  kind: d.kind,
  blocks: d.blocks.map((b) => ({ ...b })),
  claims: d.claims.map((c) => ({ ...c })),
}));

const BLOCK_TYPES = new Set(['meta', 'name', 'contact', 'section', 'role', 'para', 'bullet', 'sig']);
const slotsIn = (doc) =>
  doc.blocks.flatMap((b) => [...(b.text ?? '').matchAll(/\{\{(c\d+)\}\}/g)].map((m) => m[1]));

// The invariant the whole page rests on. A claim that cannot ship has no source.
for (const doc of documents) {
  const slots = slotsIn(doc);
  for (const block of doc.blocks) {
    if (!BLOCK_TYPES.has(block.type)) throw new Error(`${doc.id}: unknown block type ${block.type}`);
  }
  for (const slot of slots) {
    if (!doc.claims.some((c) => c.id === slot)) throw new Error(`${doc.id}: slot ${slot} has no claim`);
  }

  for (const claim of doc.claims) {
    const blocked = claim.label === 'c' || claim.label === 'd';
    if (blocked && claim.sourceId !== 's0') {
      throw new Error(`${doc.id}/${claim.id}: label ${claim.label} must carry sourceId s0, found ${claim.sourceId}`);
    }
    if (!blocked && claim.sourceId === 's0') {
      throw new Error(`${doc.id}/${claim.id}: label ${claim.label} ships, so it may not cite the null source`);
    }
    const source = sources.find((s) => s.id === claim.sourceId);
    if (!source) throw new Error(`${doc.id}/${claim.id}: unknown sourceId ${claim.sourceId}`);

    // What kind of record a claim rests on is what decides its label, so the two cannot be set
    // independently. Label a means the subject said it, and only a self-report can carry that.
    // Label b means someone or something else confirmed it, which a self-report never does.
    if (claim.label === 'a' && source.category !== 'self-report') {
      throw new Error(
        `${doc.id}/${claim.id}: label a means the subject said it, but ${source.filename} is a ${source.category}`,
      );
    }
    if (claim.label === 'b' && !['third-party record', 'system export'].includes(source.category)) {
      throw new Error(
        `${doc.id}/${claim.id}: label b needs a record that is not the subject speaking; ${source.filename} is a ${source.category}`,
      );
    }
    if (!requirements.some((r) => r.id === claim.requirementId)) {
      throw new Error(`${doc.id}/${claim.id}: unknown requirementId ${claim.requirementId}`);
    }
    if (!slots.includes(claim.id)) {
      throw new Error(`${doc.id}: no block has a slot for ${claim.id}`);
    }
  }
}

/* --------------------------------------------------------------- gates --- */

const gates = config.gates.map((g) => ({ ...g }));
const GATE_IDS = gates.map((g) => g.id);

// How each of the 13 non-focus records ends. The focus record is added separately.
// Ordering here is fixed, so the funnel numbers are reproducible by hand.
const STOPS = [
  'intake', 'intake',
  'live', 'live',
  'pressure', 'pressure',
  'wildcard',
  'lint', 'lint', 'lint',
  null, null, null, // null = reached submitted
];

const STOP_VERDICT = {
  intake: 'fail',
  live: 'expired',
  pressure: 'blocked',
  wildcard: 'blocked',
  lint: 'blocked',
};

function verdictsFor(stopGate) {
  const out = {};
  let stopped = false;
  for (const id of GATE_IDS) {
    if (stopped) {
      out[id] = 'not applicable';
    } else if (id === stopGate) {
      out[id] = STOP_VERDICT[id];
      stopped = true;
    } else {
      out[id] = 'pass';
    }
  }
  return out;
}

// Unique invented company names.
const usedCompanies = new Set([config.posting.company]);
function inventCompany() {
  for (let attempt = 0; attempt < 200; attempt += 1) {
    const name = `${pick(config.companyWords.first)} ${pick(config.companyWords.second)}`;
    if (!usedCompanies.has(name)) {
      usedCompanies.add(name);
      return name;
    }
  }
  throw new Error('ran out of unique company names; widen companyWords');
}

const targets = config.corpusTargets;

// The focus record is the application shown on the Provenance tab. Its numbers are not
// invented: they are counted from documents.json, so the two tabs cannot disagree.
const focusClaims = documents.flatMap((d) => d.claims);
const focusBlocked = focusClaims.filter((c) => c.label === 'c' || c.label === 'd').length;
const focusSourceIds = [...new Set(focusClaims.map((c) => c.sourceId))].filter((id) => id !== 's0');

// It carries claims labelled c and d, so asset lint stops it. That is the point of the demo.
const focusRecord = {
  id: 'rec-07',
  company: config.posting.company,
  role: config.posting.role,
  focus: true,
  claimsParsed: focusClaims.length,
  claimsCleared: focusClaims.length - focusBlocked,
  claimsBlocked: focusBlocked,
  sourceIds: focusSourceIds,
  stoppedAt: 'lint',
  verdicts: verdictsFor('lint'),
};

// Split the remaining claim budget across the other records: every record gets at least one,
// the remainder is distributed by weight, and the residual is corrected so the total is exact.
const otherCount = targets.records - 1;
const remainingParsed = targets.claimsParsed - focusRecord.claimsParsed;
const remainingBlocked = targets.claimsBlocked - focusRecord.claimsBlocked;

const weights = Array.from({ length: otherCount }, () => 0.35 + random());
const weightTotal = weights.reduce((a, b) => a + b, 0);
const spare = remainingParsed - otherCount;
const parsedCounts = weights.map((w) => 1 + Math.floor((w / weightTotal) * spare));
let residual = remainingParsed - parsedCounts.reduce((a, b) => a + b, 0);
for (let i = 0; residual > 0; i = (i + 1) % otherCount, residual -= 1) parsedCounts[i] += 1;

// Blocked claims belong only to records that asset lint stopped — that is what lint rejects.
const lintIndexes = STOPS.map((s, i) => (s === 'lint' ? i : -1)).filter((i) => i >= 0);
const blockedCounts = new Array(otherCount).fill(0);
for (let n = 0; n < remainingBlocked; n += 1) {
  blockedCounts[lintIndexes[n % lintIndexes.length]] += 1;
}

// A record cannot block more claims than it parsed, and a lint-stopped record must still
// ship something. Borrow from whichever record is currently largest; the total stays exact.
for (const i of lintIndexes) {
  while (parsedCounts[i] < blockedCounts[i] + 1) {
    const donor = parsedCounts.indexOf(Math.max(...parsedCounts));
    if (donor === i || parsedCounts[donor] <= blockedCounts[donor] + 1) {
      throw new Error('cannot balance claim counts; raise claimsParsed or lower claimsBlocked');
    }
    parsedCounts[donor] -= 1;
    parsedCounts[i] += 1;
  }
}

// Every source in the pool must be cited by something, or "23 sources cited" is not true.
const unassigned = realSourceIds.filter((id) => !focusSourceIds.includes(id));

const records = [];
for (let i = 0; i < otherCount; i += 1) {
  const mine = unassigned.filter((_, k) => k % otherCount === i);
  const extra = random() < 0.4 ? [pick(focusSourceIds)] : [];
  const sourceIds = [...new Set([...mine, ...extra])].sort(
    (a, b) => Number(a.slice(1)) - Number(b.slice(1)),
  );
  const stoppedAt = STOPS[i];
  records.push({
    id: `rec-${String(i + 1).padStart(2, '0')}`,
    company: inventCompany(),
    role: pick(config.roleWords),
    focus: false,
    claimsParsed: parsedCounts[i],
    claimsCleared: parsedCounts[i] - blockedCounts[i],
    claimsBlocked: blockedCounts[i],
    sourceIds,
    stoppedAt,
    verdicts: verdictsFor(stoppedAt),
  });
}
records.splice(6, 0, focusRecord);
records.forEach((r, i) => {
  r.id = r.focus ? 'rec-07' : `rec-${String(i + 1).padStart(2, '0')}`;
});

/* ----------------------------------------------------------------- runs --- */

function runLines(record) {
  const lines = [];
  for (const gate of gates) {
    const verdict = record.verdicts[gate.id];
    if (verdict === 'not applicable') break;
    const ok = verdict === 'pass';
    let text;
    if (gate.id === 'intake') {
      text = ok
        ? `${requirements.length} requirements quoted verbatim`
        : 'no verbatim requirement text found in posting';
    } else if (gate.id === 'live') {
      text = ok ? `posting live, rechecked ${config.pinnedDate}` : 'posting closed since intake';
    } else if (gate.id === 'pressure') {
      text = ok ? 'stretch — 1 must-have adjacent but honest' : 'must-have requirement lands on do not have';
    } else if (gate.id === 'wildcard') {
      text = ok ? 'answer drafted from interview_2026-03-11.txt' : 'no honest answer available';
    } else if (gate.id === 'lint') {
      text = ok
        ? `${record.claimsParsed} claims, all labelled a or b`
        : `${record.claimsBlocked} claim(s) labelled c or d`;
    } else {
      text = `${record.claimsCleared} claims shipped`;
    }
    lines.push({ gate: gate.id, status: ok ? 'ok' : verdict.toUpperCase(), text });
  }
  return lines;
}

const runs = records.map((record, i) => ({
  id: `run-${String(i + 1).padStart(4, '0')}`,
  recordId: record.id,
  company: record.company,
  role: record.role,
  lines: runLines(record),
  exit: record.stoppedAt === null ? 0 : 1,
}));

const gatesFile = { gates, records, runs };

/* -------------------------------------------------- assert, then write --- */

const sum = (list, key) => list.reduce((a, r) => a + r[key], 0);
const distinctSources = new Set(records.flatMap((r) => r.sourceIds));

const assertions = [
  ['records', records.length, targets.records],
  ['claimsParsed', sum(records, 'claimsParsed'), targets.claimsParsed],
  ['claimsCleared', sum(records, 'claimsCleared'), targets.claimsCleared],
  ['claimsBlocked', sum(records, 'claimsBlocked'), targets.claimsBlocked],
  ['sourcesCited', distinctSources.size, targets.sourcesCited],
  ['sourcePool', realSourceIds.length, targets.sourcesCited],
];
for (const [name, actual, expected] of assertions) {
  if (actual !== expected) throw new Error(`corpus ${name}: got ${actual}, config says ${expected}`);
}
if (!runs.some((r) => r.exit === 1)) throw new Error('no run exits 1; the log must show a refusal');
if (!requirements.some((r) => r.verdict === 'do not have')) {
  throw new Error('no requirement lands on do not have; the pressure test must sometimes say no');
}

function writeJson(relative, value) {
  const path = join(ROOT, relative);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
  return relative;
}

writeJson('data/generated/sources.json', sources);
writeJson('data/generated/requirements.json', requirements);
writeJson('data/generated/documents.json', documents);
writeJson('data/generated/gates.json', gatesFile);

// The page imports this instead of fetching the JSON above. Same data, no network, and it
// works from file:// and from any deploy subpath.
const module = `// Generated by scripts/generate.mjs. Do not edit by hand — run: npm run seed
export const sources = ${JSON.stringify(sources, null, 2)};

export const requirements = ${JSON.stringify(requirements, null, 2)};

export const documents = ${JSON.stringify(documents, null, 2)};

export const gates = ${JSON.stringify(gatesFile, null, 2)};

export const meta = ${JSON.stringify(
  { pinnedDate: config.pinnedDate, posting: config.posting, targets },
  null,
  2,
)};
`;
writeFileSync(join(ROOT, 'src/js/data.js'), module, 'utf8');

/* ------------------------------------------- static summary + structured data --- */

// The three main views are built by JavaScript. Crawlers that do not run JS — which includes
// most of the ones that feed answer engines — would otherwise see an empty page with four tab
// labels on it. So the same facts are also written into the HTML as a plain summary. It is
// visible to every reader, not hidden for machines: this is not the page to cloak anything on.

const escape = (value) =>
  String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const LABEL_TEXT = {
  a: 'the subject said it — supported by a self-report, ships',
  b: 'a record confirms it — supported by a third-party record or a system export, ships',
  c: 'claimed, never checked — no record, blocked',
  d: 'only in an earlier draft — traced to a document the pipeline itself wrote, blocked',
};

const answered = (doc) => {
  const state = new Map(requirements.map((r) => [r.id, 'unanswered']));
  for (const claim of doc.claims) {
    if (state.get(claim.requirementId) === 'answered') continue;
    state.set(claim.requirementId, claim.label === 'c' || claim.label === 'd' ? 'blocked' : 'answered');
  }
  return [...state.values()].filter((v) => v === 'answered').length;
};

const stopped = (gateId) => records.filter((r) => r.stoppedAt === gateId).length;
const submitted = records.filter((r) => r.stoppedAt === null).length;
const cover = documents.find((d) => d.id === 'cover');
const resume = documents.find((d) => d.id === 'resume');

const li = (items) => items.map((t) => `      <li>${t}</li>`).join('\n');

const summary = `<section class="glance" id="at-a-glance">
  <h2>At a glance</h2>

  <p>This page demonstrates grounding and refusal in a generated-document pipeline. Every factual
  claim carries the record it came from and a label grading how well that record supports it.
  Claims with no record are blocked before they reach a document, and blocking is the ordinary
  outcome rather than an error.</p>

  <h3>The four evidence labels</h3>
  <ul>
${li(Object.entries(LABEL_TEXT).map(([k, v]) => `<strong>${k}</strong> — ${v}`))}
  </ul>
  <p>Labels a and b ship. Labels c and d cannot, and a claim carrying either is required to cite
  the null record. The label and the record are one decision, not two: a self-report can only ever
  support label a, so a claim cannot be graded higher than the evidence behind it.</p>

  <h3>What the run produced</h3>
  <ul>
    <li>${targets.claimsParsed} claims parsed across ${records.length} application records.</li>
    <li>${targets.claimsCleared} claims cleared. ${targets.claimsBlocked} were blocked for want of a record.</li>
    <li>${targets.sourcesCited} distinct records in the candidate's library, across three kinds:
        self-report, third-party record, and system export.</li>
    <li>${records.length - submitted} of ${records.length} applications were refused. ${submitted} were submitted.</li>
  </ul>

  <h3>The six gates</h3>
  <ul>
${li(gates.map((g) => `<strong>${escape(g.label)}</strong> — ${escape(g.plain)} Stopped ${stopped(g.id)}.`))}
  </ul>

  <h3>The pressure test</h3>
  <p>Each requirement is given a verdict before any document is written. The overall call is
  derived from the rows, so it cannot flatter them.</p>
  <ul>
${li(requirements.map((r) => `<strong>${escape(r.title)}</strong> (${r.priority}) — ${escape(r.verdict)}.`))}
  </ul>

  <h3>The finding</h3>
  <p>The cover letter makes two claims no record supports, and answers ${answered(cover)} of
  ${requirements.length} requirements. The résumé states the smaller, true version of one of those
  claims and answers ${answered(resume)} of ${requirements.length}. The padded document scores worse
  than the honest one. Exporting the cover letter to PDF omits the unsupported claims entirely and
  prints a withheld notice in their place.</p>

  <h3>In machine-learning terms</h3>
  <p>This is grounding and citation with refusal — abstention — as the default when evidence is
  absent. Provenance is enforced in the schema rather than by a filter applied afterwards, which is
  what makes hallucinated or unsupported output unrepresentable rather than merely unlikely. The
  invariants are executable: the generator throws rather than emit a claim whose label and record
  disagree, and a check fails the build if one ever appears.</p>

  <p class="glance-note">Demo data. The candidate, employer and posting are invented; every figure
  above is produced by <code>npm run seed</code> from a fixed seed in this repository.</p>
</section>`;

const graph = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Person',
      '@id': 'https://consultruss.com/#russell-w-hild',
      name: 'Russell W. Hild',
      url: 'https://consultruss.com',
    },
    {
      '@type': 'TechArticle',
      headline: 'Designing a system that will not state what it cannot prove',
      description:
        'A working demo of grounding and refusal in a document generator. Every factual claim is ' +
        'traced to the record behind it and graded by how well that record supports it; claims with ' +
        'no record are blocked before they ship.',
      author: { '@id': 'https://consultruss.com/#russell-w-hild' },
      inLanguage: 'en',
      isAccessibleForFree: true,
      keywords: [
        'grounding', 'refusal', 'abstention', 'hallucination', 'provenance', 'citation',
        'evidence grading', 'verifiable claims', 'retrieval-augmented generation',
        'AI safety', 'document generation', 'auditability',
      ].join(', '),
      about: [
        { '@type': 'Thing', name: 'Grounding in language model output' },
        { '@type': 'Thing', name: 'Refusal and abstention under insufficient evidence' },
        { '@type': 'Thing', name: 'Provenance tracking' },
        { '@type': 'Thing', name: 'Hallucination control' },
      ],
    },
    {
      '@type': 'SoftwareSourceCode',
      name: 'provenance',
      description:
        'Static demo. A seeded generator writes job application documents, grades each claim by ' +
        'the kind of record behind it, and refuses to emit any claim it cannot source.',
      programmingLanguage: 'JavaScript',
      runtimePlatform: 'Browser, Node.js',
      author: { '@id': 'https://consultruss.com/#russell-w-hild' },
    },
  ],
};

const block = [
  '<!-- generated:summary:start — written by scripts/generate.mjs, do not edit by hand -->',
  `<script type="application/ld+json">\n${JSON.stringify(graph, null, 2)}\n</script>`,
  summary,
  '<!-- generated:summary:end -->',
].join('\n');

const indexPath = join(ROOT, 'src/index.html');
const html = readFileSync(indexPath, 'utf8');
const START = '<!-- generated:summary:start';
const END = 'generated:summary:end -->';
if (!html.includes(START) || !html.includes(END)) {
  throw new Error('src/index.html is missing the generated:summary markers');
}
const before = html.slice(0, html.indexOf(START));
const after = html.slice(html.indexOf(END) + END.length);
writeFileSync(indexPath, `${before}${block}${after}`, 'utf8');

console.log(`seed ${config.seed} · ${records.length} records · ${targets.claimsParsed} claims parsed · ` +
  `${targets.claimsBlocked} blocked · ${targets.sourcesCited} sources cited`);
console.log('wrote data/generated/*.json, src/js/data.js and the summary block in src/index.html');
